name: linux

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]
  workflow_dispatch:


jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3.0.0
        with:
          version: '6.6.*'
          setup-python: false
          modules: 'qtpositioning'
      - name: build-dor
        run: mkdir build
      - name: qmake
        run: cd build && qmake ../CloudLogOffline.pro
      - name: make
        run: cd build && make -j5
